web/router.ex
defmodule WeirdStuff.Router do
  use WeirdStuff.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WeirdStuff do
    pipe_through :browser # Use the default browser stack

    get "/", SessionController, :new
    resources "/users", UserController do
      resources "/messages", MessageController, only: [:new, :create, :index]
      resources "/devices", DeviceController, only: [:new, :create, :delete]
    end
    resources "/sessions", SessionController, only: [:new, :create, :show]
  end

  # Other scopes may use custom stacks.
  scope "/api", WeirdStuff do
    pipe_through :api

    resources "/device_messages", DeviceMessageController, only: [:show]
  end
end

web/models/user.ex
defmodule WeirdStuff.User do
  use WeirdStuff.Web, :model
  import Comeonin.Bcrypt, only: [hashpwsalt: 1]
  alias WeirdStuff.{ Message, Device }

  @primary_key {:id, :binary_id, autogenerate: true}
  @derive {Phoenix.Param, key: :id}

  schema "users" do
    field :email, :string
    field :password_digest, :string

    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true 
    has_many :sent_messages, Message, foreign_key: :sender_id
    has_many :received_messages, Message, foreign_key: :receiver_id
    has_many :devices, Device, foreign_key: :owner_id

    timestamps()
  end

  @permitted_fields ~w(email password password_confirmation)

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @permitted_fields)
    |> validate_required([:email, :password, :password_confirmation])
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email, message: "has already been taken")
    |> passwords_match
    |> lowercase_email
    |> hash_password
  end

  defp hash_password(changeset) do
    if password = get_change(changeset, :password) do
      changeset
      |> put_change(:password_digest, hashpwsalt(password))
    else
      changeset
    end
  end

  defp lowercase_email(changeset) do
    case changeset.changes do
      %{ email: email } ->
        change(changeset, %{ email: String.downcase(email) })
      _ -> changeset
    end
  end

  defp passwords_match(changeset) do
    if get_change(changeset, :password_confirmation) != get_change(changeset, :password) do
      add_error(changeset, :password, "'password' does not match 'password confirmation'")
    else
      changeset
    end
  end
end

web/controllers/user_controller.ex
defmodule WeirdStuff.UserController do
  use WeirdStuff.Web, :controller

  alias WeirdStuff.{User, Device, Message}

  plug :authorize_and_assign_user when not action in [:new, :create]

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => %{"email" => email, "password" => password, "password_confirmation" => password_confirmation }}) do
    user_params = %{ email: email,
                     password: password,
                     password_confirmation: password_confirmation }

    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: session_path(conn, :new))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    query =
      from u in User,
      where: u.id == ^id,
      preload: ^[:devices,
                received_messages: received_messages_query(id)]
    user = 
      query
      |> Repo.one

    render(conn, "show.html", user: user, devices: user.devices, messages: user.received_messages)
  end

  defp received_messages_query(id) do
    from m in Message, where: m.receiver_id == ^id, limit: 10, preload: [:sender, :receiver]
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end

  defp authorize_and_assign_user(conn, _opts) do
    current_user = get_session(conn, :current_user)
    case conn.params do
      %{"id" => user_id} ->
        if user_id == get_session(conn, :current_user).id do
            conn
        else
          conn
          |> put_flash(:error, "You are not authorized to view that.")
          |> redirect(to: user_path(conn, :index))
          |> halt()
        end
      _ ->
        if current_user == nil do
          conn
          |> put_flash(:error, "You are not authorized to view that.")
          |> redirect(to: session_path(conn, :new))
          |> halt()
        else
          conn
        end
    end
  end
end

web/views/user_view.ex
defmodule WeirdStuff.UserView do
  use WeirdStuff.Web, :view

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end
end

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :password, "Password", class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, "Password Confirmation", class: "control-label" %>
    <%= password_input f, :password_confirmation, class: "form-control" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for user <- @users do %>
      <tr>
        <td><%= user.email %></td>
        <td class="text-right">
          <%= link "Send Message", to: user_message_path(@conn, :new, user), class: "btn btn-default btn-xs" %>
          <%= if user.id == current_user(@conn).id do %>
            <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
            <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
            <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
          </td>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

web/templates/user/new.html.eex
<h2>New user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :create) %>

<%= link "Back", to: session_path(@conn, :new) %>

web/templates/user/show.html.eex
<h2 class="text-right"><%= @user.email %></h2>

<h3>Registered Devices</h3>
<%= link "Create Device", to: user_device_path(@conn, :new, @user) %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th class="text-right">Date Created</th>
    </tr>
  </thead>
  <tbody>
    <%= for device <- @devices do %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.code %></td>
        <td class="text-right">
          <%= WeirdStuff.DateBeautifier.perform(device.inserted_at) %>
        </td>
        <td>
          <%= link "Delete", to: user_device_path(@conn, :delete, @user, device), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Recent Messages</h3>
<%= link "Send Yourself a Message", to: user_message_path(@conn, :new, @user) %>
<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th>Sender</th>
      <th>Receiver</th>
      <th class="text-right">Time Sent</th>
    </tr>
  </thead>
  <tbody>
<%= for message <- @messages do %>
    <tr>
      <td><%= message.body %></td>
      <td><%= message.sender.email %></td>
      <td><%= message.receiver.email %></td>

      <td class="text-right">
        <%= WeirdStuff.DateBeautifier.perform(message.inserted_at) %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "Edit", to: user_path(@conn, :edit, @user) %><br>
<%= link "Back", to: user_path(@conn, :index) %>