web/router.ex
defmodule WeirdStuff.Router do
  use WeirdStuff.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WeirdStuff do
    pipe_through :browser # Use the default browser stack

    get "/", SessionController, :new
    resources "/users", UserController do
      resources "/messages", MessageController, only: [:new, :create, :index]
      resources "/devices", DeviceController, only: [:new, :create, :delete]
    end
    resources "/sessions", SessionController, only: [:new, :create, :show]
  end

  # Other scopes may use custom stacks.
  scope "/api", WeirdStuff do
    pipe_through :api

    resources "/device_messages", DeviceMessageController, only: [:show]
  end
end

web/views/layout_view.ex
defmodule WeirdStuff.LayoutView do
  use WeirdStuff.Web, :view

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>WeirdStuff!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if user = current_user(@conn) do %>
              <li><a class="signed-in">Signed in as <%= current_user(@conn).email %></a></li>
              <li><%= link "Users", to: user_path(@conn, :index) %></li>
              <li><%= link "Sign out", to: session_path(@conn, :show, user.id) %></li>

            <% else %>
              <li><%= link "Sign in", to: session_path(@conn, :new) %><li>
              <li><%= link "Sign up", to: user_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>